import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { auth } from "../../lib/auth";

export type UserSeed = {
  email: string;
  password: string;
  name: string;
  userId: string;
};

const USER_COUNT = 5;
const SEED_FILE = join(import.meta.dir, "user.seed.ts");

/**
 * Load credentials written by a previous `db:seed` run, if any.
 *
 * user.seed.ts is generated and gitignored, so it is absent on fresh clones
 * and in worktrees. Load it dynamically and treat "missing" as "no seeds yet"
 * so the first run bootstraps the file instead of crashing at import time.
 */
async function loadExistingSeeds(): Promise<UserSeed[]> {
  if (!existsSync(SEED_FILE)) return [];
  const mod = (await import("./user.seed")) as { userSeeds?: UserSeed[] };
  return mod.userSeeds ?? [];
}

function randomPassword(): string {
  // base64url keeps the password to safe, form-fillable characters
  return randomBytes(18).toString("base64url");
}

function generateUsers(): UserSeed[] {
  return Array.from({ length: USER_COUNT }, (_, i) => ({
    email: `user-${i + 1}@gmail.com`,
    password: randomPassword(),
    name: `User ${i + 1}`,
    userId: "",
  }));
}

function writeSeedFile(users: UserSeed[]): void {
  const records = users
    .map(
      (user) =>
        `  {\n` +
        `    email: ${JSON.stringify(user.email)},\n` +
        `    password: ${JSON.stringify(user.password)},\n` +
        `    name: ${JSON.stringify(user.name)},\n` +
        `    userId: ${JSON.stringify(user.userId)},\n` +
        `  },`,
    )
    .join("\n");

  const content = `// Generated by \`bun run db:seed\` — do not edit by hand.
import type { UserSeed } from "./seed-users";

export const userSeeds: UserSeed[] = [
${records}
];
`;

  writeFileSync(SEED_FILE, content);
}

/**
 * Create test users via Better Auth (properly hashed passwords).
 *
 * Generates 5 fresh random-password users only when user.seed.ts is still
 * empty, writing the credentials back to the file. On every subsequent run it
 * reuses the credentials already in the file, so db:seed is safe to re-run:
 * existing users are skipped (already in the DB) and the file is left untouched.
 */
export async function seedUsers(): Promise<UserSeed[]> {
  const existing = await loadExistingSeeds();
  const shouldGenerate = existing.length === 0;
  const targets = shouldGenerate ? generateUsers() : existing;

  const created: UserSeed[] = [];
  for (const user of targets) {
    try {
      const result = await auth.api.signUpEmail({
        body: { email: user.email, password: user.password, name: user.name },
      });
      created.push({ ...user, userId: result?.user?.id ?? user.userId });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes("already exists") || message.includes("duplicate")) {
        // Keep the existing credentials so the file stays in sync with the DB
        created.push(user);
      } else {
        throw error;
      }
    }
  }

  if (shouldGenerate) writeSeedFile(created);
  return created;
}
